services:
    utility.timestamp_listener:
        class: Rorschach\UtilityBundle\EventListener\TimestampListener
        arguments:
            $parameterBag: "@parameter_bag"
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }

parameters:
    utility.timestamp.timezone: Europe/Berlin